config/urls.py
from django.conf.urls.static                            import static
from django.contrib                                     import admin
from django.conf                                        import settings
from django.urls                                        import path, include


urlpatterns = [

    path('',                                include('lupay.apps.urls')),

]

if settings.DEBUG:

    import debug_toolbar

    urlpatterns = [

        path('admin/',                              admin.site.urls),
        path('__debug__/',                          include(debug_toolbar.urls)),

    ] + urlpatterns

    urlpatterns = urlpatterns + static(
                            settings.STATIC_URL, document_root=settings.STATIC_ROOT
                        )
    urlpatterns = urlpatterns + static(
                            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
                        )

lupay/apps/web/views/home/urls.py
from django.conf.urls.static                            import static
from django.contrib                                     import admin
from django.conf                                        import settings
from django.urls                                        import path, include

from lupay.apps.web.views.home.views                    import HomeView, days_from_suspension_report, \
                                                                agent_collection_report, \
                                                                payment_type_report

app_name = 'home'

urlpatterns = [

    path('',                        HomeView.as_view(),                     name='home'),
    path('suspensions/',            days_from_suspension_report,            name='suspensions'),
    path('agent_collection',        agent_collection_report,                name='agent_collection'),
    path('payments',                payment_type_report,                    name='payments'),

]

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V15</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url({% static 'images/bg-01.jpg' %});">
					<span class="login100-form-title-1">
						PROCESS REPORTS
					</span>
				</div>

                <div class="container">
                    <div class="row" style="padding-top: 50px; padding-bottom: 20px">
                        <form class="form-group form-inline" id="post_with_file_form" method="POST">
                            {% csrf_token %}

                            <div class="col-xs-6">
                                <div class="col-10">
                                    <div class="wrap-input100 validate-input m-b-26" data-validate="Input File is required">
                                        <input class="input100" required type="file" name="input_file" placeholder="Input File">
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-6" style="padding-left: 10px">
                                <input class="input100" required type="text" name="output_folder" placeholder="Output Folder">
                            </div>

                            <div class="-align-center" style="padding-left: 10px; padding-right: 15px">
                                <button class="btn btn-outline-success form-control">
                                    Submit
                                </button>
                            </div>
                        </form>
                    </div>

                    <div style="padding: 20px" align="center">
                        {% if i %}
                            <a class="btn btn-info btn-sm" href="{% url 'home:suspensions' %}?folder={{ i.folder }}">Suspension Report</a>
                            <a class="btn btn-info btn-sm" href="{% url 'home:agent_collection' %}?folder={{ i.folder }}">Agent Collections</a>
                            <a class="btn btn-info btn-sm" href="{% url 'home:payments' %}?folder={{ i.folder }}">Payment Type</a>
                        {% else %}
                            <br>
                            <br>
                        {% endif %}
                    </div>

                </div>
			</div>
		</div>
	</div>
	
    <!--===============================================================================================-->
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>